# Generated by Django 5.0.4 on 2024-05-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('non_attribue', 'Non attribué'), ('attribue', 'Attribué'), ('en_cours', 'En cours'), ('cloture', 'Cloturé')], max_length=20)),
                ('groups', models.ManyToManyField(related_name='folder', to='groups.group')),
            ],
        ),
    ]
