# Generated by Django 5.0.4 on 2024-05-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
        ('groups', '0003_alter_group_list_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='groups',
            field=models.ManyToManyField(null=True, related_name='folder', to='groups.group'),
        ),
    ]
